services:
  php:
    image: docker.io/library/php:8.5.1RC2-zts-alpine3.23
    ports:
      - "8080:8080"
    working_dir: /usr/src/karla
    command: php -S 0.0.0.0:8080
    volumes:
      - ./src:/usr/src/karla
