name: Playwright Tests
on:
  push:
    branches: [development]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: inject karla.conf file
        run: |
          cat << EOF | sudo tee /etc/karla.conf > /dev/null
          ${{ secrets.KARLA_CONF }}
          EOF

      - name: Start PHP server
        run: |
          php -S 127.0.0.1:8080 -t src > /tmp/server.log 2>&1 &

      - name: Wait for site
        run: |
          for i in {1..10}; do
            curl -sf http://localhost:8080 && exit 0
            sleep 1
          done
          echo "Site did not start" && exit 1

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Playwright Browsers
        run: |
          cd test
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd test
          npx playwright test --trace on

      - name: show server logs
        if: always()
        run: cat /tmp/server.log

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: test/playwright-report/
          retention-days: 30
